apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-ckobnlep
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-ckobnlep:276ac1c2251b9e32894cab105ddc7feef8664dc2@sha256:6090e6d643416e602a4c3ae746392b37e5af2d8e5ce96fa688f9c233f46794e5
        name: container-image  
